<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
<div class="container">
    <div class="toc" id="toc-auto"
         style="left: 890.511px; max-width: 265.838px; visibility: visible; position: fixed; top: 76px;">
        <h2 class="toc-title">目录</h2>
        <div class="toc-content" id="toc-content-auto">
            <nav id="TableOfContents">
                <ul>
                    <li class=""><a href="#以值的形式抛出-以引用的形式捕获" class="">以值的形式抛出、以引用的形式捕获</a>
                        <ul>
                            <li class=""><a href="#以值的形式抛出异常对象后-栈展开不会销毁该异常对象吗-此时如何引用到该异常对象" class="">以值的形式抛出异常对象后，栈展开不会销毁该异常对象吗？此时如何引用到该异常对象？</a>
                            </li>
                            <li class=""><a href="#为什么要以引用形式捕获异常对象" class="">为什么要以引用形式捕获异常对象？</a></li>
                            <li class=""><a href="#为什么要以值的形式抛出" class="">为什么要以值的形式抛出？</a></li>
                        </ul>
                    </li>
                    <li class="has-active"><a href="#异常类的拷贝-移动构造函数不能抛出异常" class="active">异常类的拷贝/移动构造函数不能抛出异常</a></li>
                    <li class=""><a href="#如何桥接不使用异常机制进行错误处理的代码和使用异常机制进行错误处理的代码" class="">如何桥接不使用异常机制进行错误处理的代码和使用异常机制进行错误处理的代码</a>
                    </li>
                    <li><a href="#待补充">待补充。。。</a></li>
                    <li><a href="#参考文章">参考文章</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <article class="page single"><h1 class="single-title animated flipInX">C++异常的最佳实践</h1>
        <div class="post-meta">
            <div class="post-meta-line"><span class="post-author"><a href="https://github.com/CloseToZero"
                                                                     title="Author" target="_blank"
                                                                     rel="noopener noreferrer author" class="author"><i
                    class="fas fa-user-circle fa-fw"></i>CloseToZero</a></span></div>
            <div class="post-meta-line"><i class="far fa-calendar-alt fa-fw"></i>&nbsp;<time datetime="2021-08-21">
                2021-08-21
            </time>&nbsp;<i class="fas fa-pencil-alt fa-fw"></i>&nbsp;约 2284 字&nbsp;
                <i class="far fa-clock fa-fw"></i>&nbsp;预计阅读 5 分钟&nbsp;
            </div>
        </div>
        <div class="details toc" id="toc-static" kept="">
            <div class="details-summary toc-title">
                <span>目录</span>
                <span><i class="details-icon fas fa-angle-right"></i></span>
            </div>
            <div class="details-content toc-content" id="toc-content-static"></div>
        </div>
        <div class="content" id="content"><h2 id="以值的形式抛出-以引用的形式捕获" class="headerLink"><a href="#以值的形式抛出-以引用的形式捕获"
                                                                                          class="header-mark"></a>以值的形式抛出、以引用的形式捕获
        </h2>
            <p>C++中针对异常的最佳实践中有一条：throw by value catch by reference，即以值的形式抛出、以引用的形式捕获。这会产生很多疑问，下面我们将一条条疑问列出并解决。</p>
            <h3 id="以值的形式抛出异常对象后-栈展开不会销毁该异常对象吗-此时如何引用到该异常对象" class="headerLink"><a
                    href="#以值的形式抛出异常对象后-栈展开不会销毁该异常对象吗-此时如何引用到该异常对象" class="header-mark"></a>以值的形式抛出异常对象后，栈展开不会销毁该异常对象吗？此时如何引用到该异常对象？
            </h3>
            <p>我们知道，寻找合适的异常处理块过程中，会进行栈展开（stack
                unwinding），即如果这层函数调用中，没有合适的异常处理快，会销毁这层函数调用的栈帧，回溯到上一层函数调用，在上一层函数调用中寻找合适的异常处理块，问题是销毁本层函数的栈帧，会销毁栈上分配的变量，而我们的异常对象如果是以值的形式构建的，那么该异常对象就是栈上分配的，此时栈展开就会销毁该异常对象，那么如果合适的异常处理块在上一层，该异常处理块如何以引用的形式引用到该被销毁的异常对象呢？</p>
            <p>答案是：编译器会生成代码帮忙把在栈展开过程中，把抛出的异常对象，拷贝到上一层栈帧中，
                <strong>这意味着，如果以值的形式抛出一个异常对象，我们的异常对象需要是能被拷贝的，即需要有拷贝构造函数。</strong>
                不过由于异常一般都是以临时对象形式抛出的，所以一般调用的不是拷贝构造函数，而是移动构造函数。</p>
            <p>我们可以写代码来验证栈展开过程中，异常对象会被拷贝/移动，如下：</p>
            <div class="highlight">
                <div class="chroma open">
                    <div class="code-header language-c++"><span class="code-title"><i
                            class="arrow fas fa-chevron-right fa-fw"></i></span><span class="ellipses"><i
                            class="fas fa-ellipsis-h fa-fw"></i></span><span class="copy" data-clipboard-text="#include <exception>
#include <iostream>

class MyException : public std::exception {
 public:
  explicit MyException(const char *msg) noexcept : msg_(msg) {
    std::cout << &quot;Construct MyException&quot; << std::endl;
  }

  MyException(const MyException &amp;rhs) noexcept : msg_(rhs.msg_) {
    std::cout << &quot;Copy MyException&quot; << std::endl;
  }

  const char *what() const noexcept override {
    return msg_;
  }

 private:
  const char *msg_;
};

void C() {
  throw MyException(&quot;A message&quot;);
}

void B() {
  C();
}

void A() {
  B();
}

int main() {
  try {
    A();
  } catch (const MyException &amp;e) {
    std::cout << &quot;Catch MyException: &quot; << e.what() << std::endl;
  }
}
" title="复制到剪贴板"><i class="far fa-copy fa-fw"></i></span></div>
                    <div class="table-wrapper">
                        <table class="lntable">
                            <tbody>
                            <tr>
                                <td class="lntd">
<pre class="chroma"><code><span class="lnt"> 1
</span><span class="lnt"> 2
</span><span class="lnt"> 3
</span><span class="lnt"> 4
</span><span class="lnt"> 5
</span><span class="lnt"> 6
</span><span class="lnt"> 7
</span><span class="lnt"> 8
</span><span class="lnt"> 9
</span><span class="lnt">10
</span><span class="lnt">11
</span><span class="lnt">12
</span><span class="lnt">13
</span><span class="lnt">14
</span><span class="lnt">15
</span><span class="lnt">16
</span><span class="lnt">17
</span><span class="lnt">18
</span><span class="lnt">19
</span><span class="lnt">20
</span><span class="lnt">21
</span><span class="lnt">22
</span><span class="lnt">23
</span><span class="lnt">24
</span><span class="lnt">25
</span><span class="lnt">26
</span><span class="lnt">27
</span><span class="lnt">28
</span><span class="lnt">29
</span><span class="lnt">30
</span><span class="lnt">31
</span><span class="lnt">32
</span><span class="lnt">33
</span><span class="lnt">34
</span><span class="lnt">35
</span><span class="lnt">36
</span><span class="lnt">37
</span><span class="lnt">38
</span><span class="lnt">39
</span><span class="lnt">40
</span></code></pre>
                                </td>
                                <td class="lntd">
<pre class="chroma"><code class="language-c++" data-lang="c++"><span class="cp">#include</span> <span class="cpf">&lt;exception&gt;</span><span
        class="cp">
</span><span class="cp">#include</span> <span class="cpf">&lt;iostream&gt;</span><span class="cp">
</span><span class="cp"></span>
<span class="k">class</span> <span class="nc">MyException</span> <span class="o">:</span> <span class="k">public</span> <span
            class="n">std</span><span class="o">::</span><span class="n">exception</span> <span class="p">{</span>
 <span class="k">public</span><span class="o">:</span>
  <span class="k">explicit</span> <span class="n">MyException</span><span class="p">(</span><span class="k">const</span> <span
            class="kt">char</span> <span class="o">*</span><span class="n">msg</span><span class="p">)</span> <span
            class="k">noexcept</span> <span class="o">:</span> <span class="n">msg_</span><span class="p">(</span><span
            class="n">msg</span><span class="p">)</span> <span class="p">{</span>
    <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span
            class="s">"Construct MyException"</span> <span class="o">&lt;&lt;</span> <span class="n">std</span><span
            class="o">::</span><span class="n">endl</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="n">MyException</span><span class="p">(</span><span class="k">const</span> <span
            class="n">MyException</span> <span class="o">&amp;</span><span class="n">rhs</span><span class="p">)</span> <span
            class="k">noexcept</span> <span class="o">:</span> <span class="n">msg_</span><span class="p">(</span><span
            class="n">rhs</span><span class="p">.</span><span class="n">msg_</span><span class="p">)</span> <span
            class="p">{</span>
    <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span
            class="s">"Copy MyException"</span> <span class="o">&lt;&lt;</span> <span class="n">std</span><span
            class="o">::</span><span class="n">endl</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="k">const</span> <span class="kt">char</span> <span class="o">*</span><span class="nf">what</span><span
            class="p">()</span> <span class="k">const</span> <span class="k">noexcept</span> <span
            class="k">override</span> <span class="p">{</span>
    <span class="k">return</span> <span class="n">msg_</span><span class="p">;</span>
  <span class="p">}</span>

 <span class="k">private</span><span class="o">:</span>
  <span class="k">const</span> <span class="kt">char</span> <span class="o">*</span><span class="n">msg_</span><span
            class="p">;</span>
<span class="p">};</span>

<span class="kt">void</span> <span class="nf">C</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">throw</span> <span class="n">MyException</span><span class="p">(</span><span
            class="s">"A message"</span><span class="p">);</span>
<span class="p">}</span>

<span class="kt">void</span> <span class="nf">B</span><span class="p">()</span> <span class="p">{</span>
  <span class="n">C</span><span class="p">();</span>
<span class="p">}</span>

<span class="kt">void</span> <span class="nf">A</span><span class="p">()</span> <span class="p">{</span>
  <span class="n">B</span><span class="p">();</span>
<span class="p">}</span>

<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="n">A</span><span class="p">();</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="k">const</span> <span
            class="n">MyException</span> <span class="o">&amp;</span><span class="n">e</span><span
            class="p">)</span> <span class="p">{</span>
    <span class="n">std</span><span class="o">::</span><span class="n">cout</span> <span class="o">&lt;&lt;</span> <span
            class="s">"Catch MyException: "</span> <span class="o">&lt;&lt;</span> <span class="n">e</span><span
            class="p">.</span><span class="n">what</span><span class="p">()</span> <span class="o">&lt;&lt;</span> <span
            class="n">std</span><span class="o">::</span><span class="n">endl</span><span class="p">;</span>
  <span class="p">}</span>
<span class="p">}</span>
</code></pre>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <p>（注：代码中我们在构造函数和拷贝构造函数中加了noexcept告诉编译器这两个函数不会抛出异常，其原因见：<a
                    href="#%e5%bc%82%e5%b8%b8%e7%b1%bb%e7%9a%84%e6%8b%b7%e8%b4%9d-%e7%a7%bb%e5%8a%a8%e6%9e%84%e9%80%a0%e5%87%bd%e6%95%b0%e4%b8%8d%e8%83%bd%e6%8a%9b%e5%87%ba%e5%bc%82%e5%b8%b8"
                    rel="">异常类的拷贝/移动构造函数不能抛出异常</a>）</p>
            <p>运行上面代码，输出如下：</p>
            <div class="highlight">
                <div class="chroma open">
                    <div class="code-header language-text"><span class="code-title"><i
                            class="arrow fas fa-chevron-right fa-fw"></i></span><span class="ellipses"><i
                            class="fas fa-ellipsis-h fa-fw"></i></span><span class="copy" data-clipboard-text="Construct MyException
Catch MyException: A message
" title="复制到剪贴板"><i class="far fa-copy fa-fw"></i></span></div>
                    <div class="table-wrapper">
                        <table class="lntable">
                            <tbody>
                            <tr>
                                <td class="lntd">
<pre class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span></code></pre>
                                </td>
                                <td class="lntd">
<pre class="chroma"><code class="language-text" data-lang="text">Construct MyException
Catch MyException: A message
</code></pre>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <p>异常对象并没有被拷贝，这是由于Copy elision造成的，具体参考<a href="https://en.cppreference.com/w/cpp/language/copy%5Felision"
                                                     target="_blank" rel="noopener noreferrer">Copy elision</a>。</p>
            <p>这里为了禁止Copy elision，可以传编译器选项去禁用，比如
                GCC/G++的-fno-elide-constructors，或者我们直接加个变量去引用这个异常对象，从而不满足Copy elision的使用条件，把函数C的代码改成如下：</p>
            <div class="highlight">
                <div class="chroma open">
                    <div class="code-header language-c++"><span class="code-title"><i
                            class="arrow fas fa-chevron-right fa-fw"></i></span><span class="ellipses"><i
                            class="fas fa-ellipsis-h fa-fw"></i></span><span class="copy" data-clipboard-text="void C() {
  MyException e(&quot;A message&quot;);
  throw e;
}
" title="复制到剪贴板"><i class="far fa-copy fa-fw"></i></span></div>
                    <div class="table-wrapper">
                        <table class="lntable">
                            <tbody>
                            <tr>
                                <td class="lntd">
<pre class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span><span class="lnt">4
</span></code></pre>
                                </td>
                                <td class="lntd">
<pre class="chroma"><code class="language-c++" data-lang="c++"><span class="kt">void</span> <span
        class="nf">C</span><span class="p">()</span> <span class="p">{</span>
  <span class="n">MyException</span> <span class="n">e</span><span class="p">(</span><span
            class="s">"A message"</span><span class="p">);</span>
  <span class="k">throw</span> <span class="n">e</span><span class="p">;</span>
<span class="p">}</span>
</code></pre>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <p>此时运行如下：</p>
            <div class="highlight">
                <div class="chroma open">
                    <div class="code-header language-text"><span class="code-title"><i
                            class="arrow fas fa-chevron-right fa-fw"></i></span><span class="ellipses"><i
                            class="fas fa-ellipsis-h fa-fw"></i></span><span class="copy" data-clipboard-text="Construct MyException
Copy MyException
Catch MyException: A message
" title="复制到剪贴板"><i class="far fa-copy fa-fw"></i></span></div>
                    <div class="table-wrapper">
                        <table class="lntable">
                            <tbody>
                            <tr>
                                <td class="lntd">
<pre class="chroma"><code><span class="lnt">1
</span><span class="lnt">2
</span><span class="lnt">3
</span></code></pre>
                                </td>
                                <td class="lntd">
<pre class="chroma"><code class="language-text" data-lang="text">Construct MyException
Copy MyException
Catch MyException: A message
</code></pre>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <p>
                可以看到，虽然main到C之间有三次栈展开（C的、B的、A的），但是只有一次拷贝，换句话来说，并不是每次栈展开都拷贝，而是不管多少层调用，都只拷贝一次，要做到这个不难，可以现在栈上搜索匹配的异常处理块所在的栈帧，然后先执行拷贝，拷贝完后，再开始栈展开。</p>
            <h3 id="为什么要以引用形式捕获异常对象" class="headerLink"><a href="#为什么要以引用形式捕获异常对象" class="header-mark"></a>为什么要以引用形式捕获异常对象？
            </h3>
            <p>理由应该是比较简单的：减少一次不必要的拷贝。</p>
            <p>除此之外，标准还说，异常对象会被视为左值，故即使它是临时对象，也可以绑定在非const引用上。</p>
            <h3 id="为什么要以值的形式抛出" class="headerLink"><a href="#为什么要以值的形式抛出" class="header-mark"></a>为什么要以值的形式抛出？</h3>
            <p>为什么要以值的形式抛出，为什么不new一个异常对象，抛出该异常对象，这样做会有什么问题吗？</p>
            <p>
                new一个对象，我们就得考虑如何保证该对象被释放，首先，该对象在被捕获之前以及在被捕获后异常处理块的代码执行过程中，都是不能被释放的。那异常处理块执行完后呢？谁去负责释放？似乎只有两个候选人了，即捕获该异常的异常处理块或者让编译器在异常处理块中自动插入释放异常的代码，前者由于每个异常处理块都得写释放逻辑，代码重复量大，易漏写，只有后者可行点。</p>
            <p>
                即使编译器可以帮插代码去释放，还得考虑一个问题：如果在new一个异常对象的过程中，new抛出异常，那该新异常会替代原始异常，寻找对应的异常处理块以及在必要时进行栈展开，这个过程是不可恢复的，故老异常直接丢失，此时我们就没办法知道原本发生异常的原因了，这会导致异常处理不可靠。</p>
            <h2 id="异常类的拷贝-移动构造函数不能抛出异常" class="headerLink"><a href="#异常类的拷贝-移动构造函数不能抛出异常" class="header-mark"></a>异常类的拷贝/移动构造函数不能抛出异常
            </h2>
            <p>前面我们在 <a
                    href="#%e4%b8%ba%e4%bb%80%e4%b9%88%e8%a6%81%e4%bb%a5%e5%80%bc%e7%9a%84%e5%bd%a2%e5%bc%8f%e6%8a%9b%e5%87%ba"
                    rel="">为什么要以值的形式抛出？</a>
                中也说过抛出异常会导致的问题了。这里原因是差不多的，如果允许异常类的拷贝构造函数抛出异常，那新抛出的异常会替代原始异常，寻找对应的异常处理块以及在必要时进行栈展开，这个过程是不可恢复的，老异常直接丢失，此时我们就没办法知道原本发生异常的原因了，这会导致异常处理不可靠，于是标准要求异常类的拷贝构造函数不能抛出异常（同理，如果抛出的是临时异常对象，导致用的是移动构造函数，那移动构造函数也不能抛出异常），更进一步的，标准要求：如果在异常类的拷贝构造函数中抛出异常，会直接调用std::terminate结束程序。
            </p>
            <p>综上，我们应该要保证异常类的拷贝/移动构造函数不抛出异常，并加上
                noexcept修饰符，同理，为了不要掩盖发生异常的真实原因（见：<a
                        href="#%e4%b8%ba%e4%bb%80%e4%b9%88%e8%a6%81%e4%bb%a5%e5%80%bc%e7%9a%84%e5%bd%a2%e5%bc%8f%e6%8a%9b%e5%87%ba"
                        rel="">为什么要以值的形式抛出？</a>），构造函数也应该不要抛出异常，也应该加上noexcept修饰符。</p>
            <p>由于常用的std::string类的拷贝构造函数是可能会抛出异常的，故在异常类中不应该内嵌std::string类，这点在boost的错误处理文档中也有提及，具体见：
                <a href="https://www.boost.org/community/error%5Fhandling.html" target="_blank"
                   rel="noopener noreferrer">Error and Exception Handling</a>。</p>
            <h2 id="如何桥接不使用异常机制进行错误处理的代码和使用异常机制进行错误处理的代码" class="headerLink"><a
                    href="#如何桥接不使用异常机制进行错误处理的代码和使用异常机制进行错误处理的代码" class="header-mark"></a>如何桥接不使用异常机制进行错误处理的代码和使用异常机制进行错误处理的代码
            </h2>
            <p>以Windows
                API和POSIX定义的接口为例，这两者都是通过错误码来报告异常的，要么是通过返回值来，要么是把最近一次的错误码存在线程局部存储区域（典型的：GetLastError和errno）。如果我们的C++代码需要调用这些接口，那该怎么进行错误处理？我们当然是希望统一通过异常来进行错误处理的，如何做到这一点，可以参考：<a
                        href="https://docs.microsoft.com/en-us/cpp/cpp/how-to-interface-between-exceptional-and-non-exceptional-code?view=msvc-160"
                        target="_blank" rel="noopener noreferrer">How to: Interface between exceptional and
                    non-exceptional code</a>。</p>
            <h2 id="待补充" class="headerLink"><a href="#待补充" class="header-mark"></a>待补充。。。</h2>
            <h2 id="参考文章" class="headerLink"><a href="#参考文章" class="header-mark"></a>参考文章</h2>
            <ol>
                <li><a href="https://en.cppreference.com/w/cpp/language/copy%5Felision" target="_blank"
                       rel="noopener noreferrer">Copy elision</a></li>
                <li><a href="https://www.boost.org/community/error%5Fhandling.html" target="_blank"
                       rel="noopener noreferrer">Error and Exception Handling</a></li>
                <li>
                    <a href="https://docs.microsoft.com/en-us/cpp/cpp/how-to-interface-between-exceptional-and-non-exceptional-code?view=msvc-160"
                       target="_blank" rel="noopener noreferrer">How to: Interface between exceptional and
                        non-exceptional code</a></li>
                <li>
                    <a href="https://stackoverflow.com/questions/28932115/c-exceptions-throw-by-value-catch-by-reference"
                       target="_blank" rel="noopener noreferrer">c++ exceptions throw by value catch by reference</a>
                </li>
                <li><a href="https://stackoverflow.com/questions/10948316/throw-new-stdexception-vs-throw-stdexception"
                       target="_blank" rel="noopener noreferrer">throw new std::exception vs throw std::exception</a>
                </li>
                <li><a href="https://stackoverflow.com/questions/58955178/why-are-c-exceptions-potentially-copied"
                       target="_blank" rel="noopener noreferrer">Why are C++ exceptions (potentially) copied</a></li>
            </ol>
        </div>
        <div class="post-footer" id="post-footer">
            <div class="post-info">
                <div class="post-info-line">
                    <div class="post-info-mod">
                        <span>更新于 2021-08-21</span>
                    </div>
                    <div class="post-info-license"></div>
                </div>
                <div class="post-info-line">
                    <div class="post-info-md"></div>
                    <div class="post-info-share">
                        <span></span>
                    </div>
                </div>
            </div>

            <div class="post-info-more">
                <section class="post-tags"><i class="fas fa-tags fa-fw"></i>&nbsp;<a href="/tags/c++/">c++</a>,&nbsp;<a
                        href="/tags/%E5%BC%82%E5%B8%B8/">异常</a></section>
                <section>
                    <span><a href="javascript:void(0);"
                             onclick="window.history.back();">返回</a></span>&nbsp;|&nbsp;<span><a href="/">主页</a></span>
                </section>
            </div>

            <div class="post-nav"><a href="/20210812203511-windows_wow64%E5%8E%9F%E7%90%86/" class="prev" rel="prev"
                                     title="Windows WOW64原理"><i class="fas fa-angle-left fa-fw"></i>Windows WOW64原理</a>
                <a href="/20210914000000-%E9%99%B6%E5%93%B2%E8%BD%A9analysis_i%E4%B9%A0%E9%A2%98%E7%9A%84%E5%8F%82%E8%80%83%E8%A7%A3%E7%AD%94%E5%8F%8A%E6%80%9D%E8%80%83_%E7%AC%AC2%E7%AB%A0/"
                   class="next" rel="next" title="陶哲轩Analysis I习题的参考解答及思考（第2章）">陶哲轩Analysis I习题的参考解答及思考（第2章）<i
                        class="fas fa-angle-right fa-fw"></i></a></div>
        </div>
    </article>
</div>
</body>
</html>
